# Generated by Django 3.0.6 on 2020-05-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200527_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_method',
            field=models.CharField(blank=True, choices=[('signup', 'Signup'), ('github', 'Github'), ('kakao', 'Kakao'), ('naver', 'Naver')], default='signup', max_length=50, null=True),
        ),
    ]
